banking_dbt:
  outputs:
    dev:
      account: QJCBHGQ-OR10124
      database: banking
      password: BabaiBabai@#2001
      role: accountadmin
      schema: raw
      threads: 1
      type: snowflake
      user: nandkumarsh222
      warehouse: COMPUTE_WH
  target: dev
